export interface Hazard {
    id: string,
    code: string,
    title: string,
    description: string,
    comment: string,
    routeCause: string,
    areaId: string,
    cityId: string,
    stateId: string,
    countryId: string,
    reportedHazardLatitude: string,
    reportedHazardLongitude: string,
    serialNumber: number,
    suggestion: string,
    assignerId: string,
    assigneeId: string,
    assignedDepartmentId: string,
    assignedOrganizationId: string,
    reporterName: string,
    reporterEmail: string,
    reporterFirstResponderAction: string,
    reporterFeedbackRating: number,
    managerFeedbackRating: number,
    reporterDepartmentId: string,
    incidenceStatusId: string, //to change to hazardStatusId
    resolutionDate: string,
    address: string
}