export interface SaveDepartmentDetail {
    id: string,
    code: string,
    name: string,
    description: string,
    hostName: string,
    port: number,
    email1: string,
    email2: string,
    phone1: string,
    phone2: string,
    maxImageFileSize: number,
    maxVideoFileSize: number,
    acceptedVideoFileTypes: string,
    acceptedImageFileTypes: string,
    smsServiceProvider: string,
    entityName: string,
    sendSMS: boolean,
    activateEmailSenderSettings: boolean,
    activateFileSettings: boolean,
    emailSendersEmail: string,
    emailSenderName: string,
    emailSenderPassword: string,
    emailRecipientAddresses: string,
    smsRecipientNumbers: string
}
