export interface SystemSettings {
    id: string,
    enableBranding: string,
    brandTitle: string,
    brandIcon: string,
    useSsl: boolean,
    hostName: string,
    port: number,
    pageSize: number,
    email1: string,
    email2: string,
    phone1: string,
    phone2: string,
    maxImageFileSize: number,
    maxVideoFileSize: number,
    acceptedVideoFileTypes: string,
    acceptedImageFileTypes: string,
    smsServiceProvider: string,
    entityName: string,
    sendSMS: boolean,
    emailSendersEmail: string,
    emailSenderName: string,
    emailSenderPassword: string
}
